spring:
  ai:
    mcp:
      client:
        stdio:
         servers-configuration: classpath:mcp-servers.json
#        sse:
#          connections:
#            server1:
#              url: http://localhost:9977

  application:
    name: var-ai-agent
  profiles:
    active: local
server:
  port: 33333
  servlet:
    context-path: /api # api接口前缀
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.varin.varaiagent.controller #对应Controller接口包路径
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


